### ISSUE TITLE
Latest version errors

### ISSUE THREAD

**Issue by pausanchezv** [tomasvotava/fastapi-sso#165]
The latest version shows this error (a lot). it didn't use to happen with older versions:

```
Traceback: Traceback (most recent call last):
File "/app/app/views/auth.py", line 69, in facebook_callback
open_id_user: OpenID = await facebook_sso.verify_and_process(request)
File "/usr/local/lib/python3.10/site-packages/fastapi_sso/sso/base.py", line 359, in verify_and_process
return await self.process_login(
File "/usr/local/lib/python3.10/site-packages/fastapi_sso/sso/base.py", line 506, in process_login
return await self.openid_from_response(content, session)
File "/usr/local/lib/python3.10/site-packages/fastapi_sso/sso/facebook.py", line 29, in openid_from_response
return OpenID(
File "pydantic/main.py", line 341, in pydantic.main.BaseModel.init
pydantic.error_wrappers.ValidationError: 1 validation error for OpenID
email
value is not a valid email address (type=value_error.email)
```

Hope you can fix this soon.

Thanks.

**Comment by tomasvotava** [comment]
Hi, it's a shame we don't get to see the actual value that facebook sends. There used to be `str` instead of `EmailStr` in the older versions, but it would be beneficial to actually know why Facebook is not responding with a valid e-mail address. I'll look into it, thanks for bringing this up!

**Comment by tomasvotava** [comment]
Ok, it seems Facebook / Meta or whatever they prefer to be called lately is not making things easy, sometimes it just does not return any e-mail, you could try investigating using their Graph API Explorer, but unfortunately it seems like it's different for each user based on their profile settings.
Anyways, there was a stupid bug in FacebookSSO that made missing e-mail into `""` instead of `None`. I will publish fix for that ASAP. Thanks!

**Comment by pausanchezv** [comment]
Thank you!
