### ISSUE TITLE
Error using code from microsoft sso example

### ISSUE THREAD

**Issue by mrdeveloperdude** [tomasvotava/fastapi-sso#49]
Here is my relevant code:

```

sso = MicrosoftSSO(
	client_id = MICROSOFT_SSO_CLIENT_ID,
	client_secret = MICROSOFT_SSO_CLIENT_SECRET,
	tenant = MICROSOFT_SSO_TENANT,
	redirect_uri= f"{MICROSOFT_SSO_REDIRECT_URL}/admin/auth/callback",
	allow_insecure_http = True,
	scope=["openid", "email"]
)


@admin_route.get("/auth/login")
async def auth_init(request: Request):
	"""Initialize auth and redirect"""
	with sso:
		return await sso.get_login_redirect(redirect_uri=request.url_for("auth_callback"))


@admin_route.get("/auth/callback")
async def auth_callback(request: Request):
	"""Verify login"""
	logger.info(f"GOT CALLBACK: {await request.body()}")
	with sso:
		return await sso.verify_and_process(request)
```

It is pretty much identical to the example. When I go to the login url, I am redirected successfully to microsoft and back, but with the last call "return await sso.verify_and_process(request)"

I get the following error:
```
fastapi_1   | ERROR:    Exception in ASGI application
fastapi_1   | Traceback (most recent call last):
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
fastapi_1   |     result = await app(  # type: ignore[func-returns-value]
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
fastapi_1   |     return await self.app(scope, receive, send)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 282, in __call__
fastapi_1   |     await super().__call__(scope, receive, send)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
fastapi_1   |     await self.middleware_stack(scope, receive, send)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
fastapi_1   |     raise exc
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
fastapi_1   |     await self.app(scope, receive, _send)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
fastapi_1   |     raise exc
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
fastapi_1   |     await self.app(scope, receive, sender)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
fastapi_1   |     raise e
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
fastapi_1   |     await self.app(scope, receive, send)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
fastapi_1   |     await route.handle(scope, receive, send)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
fastapi_1   |     await self.app(scope, receive, send)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
fastapi_1   |     response = await func(request)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 241, in app
fastapi_1   |     raw_response = await run_endpoint_function(
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
fastapi_1   |     return await dependant.call(**values)
fastapi_1   |   File "/arriba/app/routes/admin.py", line 158, in auth_callback
fastapi_1   |     return await sso.verify_and_process(request)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/fastapi_sso/sso/base.py", line 212, in verify_and_process
fastapi_1   |     return await self.process_login(
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/fastapi_sso/sso/base.py", line 292, in process_login
fastapi_1   |     return await self.openid_from_response(content)
fastapi_1   |   File "/usr/local/lib/python3.9/site-packages/fastapi_sso/sso/microsoft.py", line 45, in openid_from_response
fastapi_1   |     return OpenID(email=response["mail"], display_name=response["displayName"], provider=cls.provider)
fastapi_1   | KeyError: 'mail'
```

I have tried to debug this by printing the actual request in the callback but it offers no clues. The request body is empty from Microsoft.

Why does this error occur? What are the supposed "mail" and "displayName" values that I am missing?

Any hints are welcome. Thanks!

**Comment by tomasvotava** [comment]
Done, if you use the latest `fastapi-sso==0.7.2`, it should work well. Let me know if there's any trouble.

**Comment by hart-james** [comment]
I have been trying relentlessly to get an email address from Microsoft using this library. I have tried using different releases, scopes, and the sample code. Is there any special way to get the email from Microsoft. I did not think it would be appropriate to open a new issue.
